In [44]:
import pandas as pd
import random
data=pd.read_excel("ranks.xlsx")

In [45]:
def fillout(x):
    if pd.isnull(x):
        newGPA=random.uniform(6,9)
        return round(newGPA,2)
    else:
        return x

In [46]:
data['CGPA']=data['CGPA'].apply(fillout)

In [47]:
data['SGPA']=data['SGPA'].apply(fillout)

In [48]:
def change(y):
    #sem=random.randint(1,6)
    sem=6
    return sem

In [49]:
data['SEMESTER']=data['SEMESTER'].apply(change)

In [50]:
data

,STUDENT REGISTRATION NUMBER,STUDENT NAME,DEPARTMENT,SEMESTER,SGPA,CGPA
0,210614100001,SUBRAT SAHU,BCA,6,8.78,6.95
1,210614100002,SUMIT TIRKEY,BCA,6,7.39,6.71
2,210614100003,TAPAS DASH,BCA,6,7.38,8.95
3,210614100004,TARANISEN BHOI,BCA,6,6.37,8.52
4,210614100005,ARYAMAN SAHOO,BCA,6,7.39,7.53
5,210614100007,BABUL KARNA,BCA,6,7.23,8.13
6,210614100008,BIJAYANI BIDYADHAR,BCA,6,7.77,6.99
7,210614100009,BIKASH RANA,BCA,6,7.31,6.54
8,210614100010,GANGADHAR ROUT,BCA,6,8.03,6.75
9,210614100011,HARESH SAHU,BCA,6,7.82,8.97
10,210614100012,HRITIK MAHANANDA,BCA,6,8.34,8.89
11,210614100013,SALONIKA PANDA,BCA,6,8.07,6.65
12,210614100014,SHILPI KUMARI,BCA,6,6.07,6.83
13,210614100015,ANSHUMAN RATH,BCA,6,8.84,7.92
14,210614100016,ARPITA BEHERA,BCA,6,7.11,7.10
15,210614100017,GEETANJALI MEHER,BCA,6,6.95,8.78
16,210604100001,JATIN SAHU,BSC(CHE),6,8.78,6.50
17,210604100002,SHREEYA PANIGRAHI,BSC(CHE),6,6.95,7.42
18,210604100003,ARPITA PADHAN,BSC(CHE),6,8.21,6.11
19,210604110002,MANISKA SAHU,BSC(MAT),6,7.43,6.24
20,210604110003,POOJA SAHU,BSC(MAT),6,6.18,8.71
21,210604120001,ABANI KARTI,BSC(PHY),6,6.18,8.06
22,210604120002,ARPITA HOTA,BSC(PHY),6,8.23,7.37
23,210604120003,LINGARAJ BEHERA,BSC(PHY),6,7.29,8.20
24,210604120004,OMKAR SAHU,BSC(PHY),6,8.23,6.98
25,210604140001,ADARSHA NANDA,BSC(IT),6,8.89,6.30
26,210604140002,ABHINAV BAGARTY,BSC(IT),6,7.37,8.93
27,210604140004,DEBASMITH PRADHAN,BSC(IT),6,6.94,7.39
28,210604140005,SHIBANANDA SAHOO,BSC(IT),6,8.34,6.73
29,210604160001,PRIYANKA SAHOO,BSC(BOT),6,8.33,6.57
30,210604160002,SHRIYARANI HOTA,BSC(BOT),6,6.83,8.54
31,210604160003,SRUSTIMAYEE SAHU,BSC(BOT),6,8.39,8.86
32,210604160004,SWAGAT PUROHIT,BSC(BOT),6,8.32,6.94
33,210604160005,PRATYUSHNA MISHRA,BSC(BOT),6,8.24,8.44
34,210604160006,SUBHRANKITA TRIPATHY,BSC(BOT),6,7.60,6.94
35,210604160007,ELIZA NAYAK,BSC(BOT),6,8.72,7.19
36,210604160008,CHANDRAKANTA BHOI,BSC(BOT),6,7.60,7.48
37,210604170001,SNEHA SINGH,BSC(ZOO),6,7.69,8.66
38,210604170003,SUBHADARSHINI HOTA,BSC(ZOO),6,8.77,8.75
39,210604170004,MADHUSMITA PRADHAN,BSC(ZOO),6,7.61,7.31
40,210604170005,NIHAR SATAPATHY,BSC(ZOO),6,7.19,8.84
41,210604170006,NIHARIKA BEHERA,BSC(ZOO),6,7.90,8.47
42,210604170007,PRAKRUTI PASAYAT,BSC(ZOO),6,6.79,8.16
43,210604170008,SHIKHA SAI,BSC(ZOO),6,7.60,6.91
44,210604170009,SMRUTI MISHRA,BSC(ZOO),6,7.99,8.85
45,210604170010,BIDYUT SAHU,BSC(ZOO),6,7.67,7.51
46,210604170011,LALITENDU SAHOO,BSC(ZOO),6,7.99,8.92
47,210604170012,ANWESHA MAHAKUR,BSC(ZOO),6,8.08,6.11
48,210604170013,BINAYA BHOI,BSC(ZOO),6,7.18,6.61
49,210604170014,RASESWARI SAHU,BSC(ZOO),6,6.83,7.61
50,210604170015,SMITA KUMAR,BSC(ZOO),6,6.07,6.65
51,210604170016,MOLISKA PATTNAIK,BSC(ZOO),6,6.25,6.82
52,210604170017,ANISHA BHOI,BSC(ZOO),6,7.31,7.44

In [51]:
data.to_excel("anishh.xlsx",index=False)